# Generated by Django 4.2.1 on 2023-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('dia', models.IntegerField(verbose_name='Dia')),
                ('mes', models.IntegerField(verbose_name='Mes')),
            ],
        ),
    ]
